[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

# Pretty URLs
[[redirects]]
  from = "/*/index.html"
  to = "/:splat/"
  status = 301
  force = true

# Security/Caching headers (tweak as needed)
[[headers]]
  for = "/assets/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
