backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "src/assets/images"
public_folder: "/assets/images"

site_url: "https://<your-site>.netlify.app"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Minwoo Jung" }
      - { label: "Section", name: "section", widget: "select", options: ["Politics", "Business", "Tech", "Culture"] }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/article-layout.njk" }
      - { label: "Tags", name: "tags", widget: "list", default: ["articles"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site"
        name: "site"
        file: "src/_data/site.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Href", name: "href", widget: "string" }
