backend:
  name: github
  repo: seongwonkc/theargosy
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"   # temporary just to test login
    create: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "body",  label: "Body", widget: "markdown" }
