backend:
  name: github
  repo: seongwonkc/theargosy
  branch: main

# uploads go under src so Eleventy copies them
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: posts
    label: Posts
    folder: "src/posts"   # <- IMPORTANT
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Author, name: author, widget: string, required: false }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Body, name: body, widget: markdown }
  - name: pages
    label: Pages
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
